# Generated by Django 5.0.3 on 2024-04-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_status_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='date_canceled',
            field=models.DateTimeField(null=True),
        ),
    ]
