# Generated by Django 5.0.3 on 2024-04-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
