# Generated by Django 5.0.3 on 2024-04-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_exportproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery_instructor',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
