# Generated by Django 5.0.3 on 2024-04-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_shippingaddress_delivery_instructor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='delivery_instructor',
            new_name='delivery_instruction',
        ),
    ]
