# Generated by Django 5.0.3 on 2024-04-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_delivery_instructor_shippingaddress_delivery_instruction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='delivery_instruction',
            field=models.CharField(choices=[('1', 'Home (7am-9pm, all days)'), ('2', 'Office (9am-6pm, Weekdays)')], max_length=200, null=True),
        ),
    ]
