# Generated by Django 5.0.3 on 2024-04-14 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_favitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price2',
            field=models.IntegerField(null=True),
        ),
    ]
