# Generated by Django 5.0.3 on 2024-04-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_product_price_product_price1_product_price2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(choices=[('1', 'sale'), ('2', 'out of stock')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
