# Generated by Django 5.0.3 on 2024-04-14 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_product_label_alter_product_price2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='label',
        ),
    ]
